import type { Blackboard } from "../types.js";

function esc(s: string): string {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

export interface HtmlExportCounts {
  nodes: number;
  edges: number;
}

export function renderBlackboardExportHtml(bb: Blackboard): { html: string; counts: HtmlExportCounts } {
  const viewModel = {
    id: bb.id, task: bb.task, iteration: bb.iteration,
    entries: bb.entries,
    signals: bb.signals,
    documents: bb.documents.map(({ text, ...d }) => d),
    created_at: bb.created_at, updated_at: bb.updated_at,
  };
  const stateJson = JSON.stringify(viewModel).replace(/</g, "\\u003c").replace(/>/g, "\\u003e");

  const entries = bb.entries;
  const signals = bb.signals;
  const edges: Array<{ s: string; t: string; k: string }> = [];
  for (const e of entries) {
    for (const t of e.supports_entries) edges.push({ s: e.id, t, k: "supports" });
    for (const t of e.contradicts_entries) edges.push({ s: e.id, t, k: "contradicts" });
    for (const t of e.supersedes_entries) edges.push({ s: e.id, t, k: "supersedes" });
  }

  const activeEntries = entries.filter(e => e.status === "active").length;
  const disputedEntries = entries.filter(e => e.status === "disputed").length;
  const openSignals = signals.filter(s => s.status === "open").length;
  const avgConf = entries.length ? entries.reduce((s, e) => s + (e.confidence || 0), 0) / entries.length : 0;

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="dark">
<title>${esc(bb.task)} — Blackboard MCP</title>
<meta name="description" content="Interactive AI reasoning trace generated by Blackboard MCP.">
<meta property="og:title" content="${esc(bb.task)} — Blackboard MCP">
<meta property="og:description" content="${entries.length} findings, ${signals.length} signals — watch an AI reason step by step.">
<style>
:root{
  --bg:#06070a;--panel:rgba(13,17,25,.88);--panel2:rgba(18,24,35,.94);
  --line:rgba(155,176,210,.16);--strong:rgba(195,212,240,.32);
  --text:#edf3ff;--muted:#8d9bb3;--soft:#c1cbe0;--accent:#48d7ff;
  --good:#69f0ae;--warn:#ffc857;--bad:#ff5c7a;
  --obs:#6dd6ff;--anl:#c792ea;--calc:#ffd166;--str:#7ee787;--gap:#ff7b72;
  --radius:8px;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  --sans:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
}
*{box-sizing:border-box;margin:0}html,body{width:100%;height:100%;overflow:hidden}
body{font-family:var(--sans);color:var(--text);background:
  radial-gradient(circle at 25% 0%,rgba(72,215,255,.16),transparent 34%),
  radial-gradient(circle at 76% 18%,rgba(199,146,234,.13),transparent 32%),
  linear-gradient(135deg,#050609,#0a0d13 48%,#050609)}
.shell{display:grid;grid-template-rows:60px minmax(0,1fr) 54px;height:100vh}
.topbar{display:flex;justify-content:space-between;align-items:center;padding:0 16px;
  border-bottom:1px solid var(--line);background:rgba(6,7,10,.82);backdrop-filter:blur(18px);z-index:5}
.title h1{font-size:17px;line-height:1.2;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.meta{display:flex;gap:6px;margin-top:4px;color:var(--muted);font-size:11px}
.chip{display:inline-flex;align-items:center;padding:2px 7px;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.04);font-size:11px}
.actions{display:flex;gap:6px;align-items:center}
.actions button{padding:6px 12px;font-size:12px}
.workspace{display:grid;grid-template-columns:280px minmax(0,1fr) 340px;min-height:0}
aside{overflow-y:auto;scrollbar-width:thin;scrollbar-color:var(--line) transparent;background:linear-gradient(180deg,rgba(9,12,18,.96),rgba(7,9,14,.92))}
.left{border-right:1px solid var(--line)}.right{border-left:1px solid var(--line);overflow-x:hidden;word-wrap:break-word;overflow-wrap:break-word}
.panel{padding:12px;border-bottom:1px solid var(--line);min-width:0;overflow-wrap:break-word}
.panel h2{margin:0 0 4px;color:var(--soft);font-size:10px;text-transform:uppercase;letter-spacing:.08em}
.panel-desc{color:var(--muted);font-size:10.5px;line-height:1.35;margin-bottom:8px}
.search{width:100%;height:34px;padding:0 10px;color:var(--text);background:rgba(0,0,0,.26);border:1px solid var(--line);border-radius:var(--radius);outline:none;font-size:13px}
.search:focus{border-color:var(--accent)}
input[type=range]{width:100%;margin:8px 0;accent-color:var(--accent)}
.filter-row{display:flex;flex-wrap:wrap;gap:5px}
button{color:var(--text);background:rgba(255,255,255,.05);border:1px solid var(--line);border-radius:var(--radius);cursor:pointer;transition:.12s}
button:hover,button.on{border-color:var(--accent);background:rgba(72,215,255,.12)}
.mg{display:grid;grid-template-columns:1fr 1fr;gap:6px}
.mc{padding:8px;border:1px solid var(--line);border-radius:var(--radius);background:rgba(255,255,255,.035)}
.mc b{display:block;font-size:22px;line-height:1}.mc span{display:block;margin-top:4px;color:var(--muted);font-size:11px}
.hist{display:grid;grid-template-columns:repeat(10,1fr);gap:3px;align-items:end;height:70px}
.hist i{display:block;min-height:2px;border-radius:3px 3px 0 0;background:linear-gradient(180deg,var(--accent),rgba(72,215,255,.22))}
.stage{position:relative;min-width:0;min-height:0;background-size:32px 32px;background-image:
  linear-gradient(rgba(255,255,255,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.03) 1px,transparent 1px)}
#graph{position:absolute;inset:0;width:100%;height:100%}
.hud{position:absolute;top:12px;left:12px;padding:6px 10px;border:1px solid var(--strong);border-radius:var(--radius);
  background:rgba(6,7,10,.74);backdrop-filter:blur(14px);color:var(--muted);font:11px var(--mono);pointer-events:none}
.tooltip{display:none;position:absolute;max-width:340px;padding:10px;border:1px solid var(--strong);border-radius:var(--radius);
  background:rgba(6,7,10,.88);backdrop-filter:blur(14px);color:var(--soft);font-size:12px;line-height:1.4;z-index:4;pointer-events:none;
  box-shadow:0 16px 48px rgba(0,0,0,.5)}
.minimap{position:absolute;right:12px;bottom:12px;width:160px;height:110px;border:1px solid var(--strong);border-radius:var(--radius);
  background:rgba(6,7,10,.74);backdrop-filter:blur(14px);overflow:hidden}
.minimap canvas{width:100%;height:100%}
.timeline{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:8px 16px;
  border-top:1px solid var(--line);background:rgba(6,7,10,.88);backdrop-filter:blur(18px);z-index:5}
.stamp{color:var(--muted);font:11px var(--mono);text-align:right}
.item{display:block;width:100%;text-align:left;padding:8px;border:1px solid var(--line);border-radius:var(--radius);
  background:rgba(255,255,255,.035);margin-bottom:6px;cursor:pointer;transition:.12s}
.item:hover{border-color:var(--accent);background:rgba(72,215,255,.06)}
.item b{font-size:11px}.item p{margin:3px 0 0;color:var(--muted);font-size:11px;line-height:1.35}
.bar{height:6px;overflow:hidden;border-radius:999px;background:rgba(255,255,255,.08);margin-top:6px}
.bar>i{display:block;height:100%;border-radius:999px;transition:width .3s}
.bar-good>i{background:linear-gradient(90deg,var(--good),rgba(105,240,174,.6))}
.bar-conv>i{background:linear-gradient(90deg,var(--bad),var(--warn),var(--good))}
.kv{display:grid;grid-template-columns:100px minmax(0,1fr);gap:4px 8px;margin-top:8px;font-size:11px;overflow-wrap:break-word;word-break:break-word}
.kv div:nth-child(odd){color:var(--muted)}
.evidence{margin-top:10px;padding:8px;border-left:3px solid var(--accent);background:rgba(72,215,255,.06);color:var(--soft);font-size:11px;line-height:1.4;border-radius:0 var(--radius) var(--radius) 0;overflow-wrap:break-word;word-break:break-word}
.footer-note{color:var(--muted);font-size:10px;text-align:center}
.footer-note a{color:var(--accent);text-decoration:none}

/* Guide overlay — hidden by default for poster-view first screenshot */
.guide-overlay{position:fixed;inset:0;z-index:100;display:none;align-items:center;justify-content:center;
  background:rgba(4,5,8,.88);backdrop-filter:blur(24px);animation:fadeIn .3s ease}
.guide-overlay.show{display:flex}
.guide-card{max-width:560px;width:90%;padding:32px;border:1px solid var(--strong);border-radius:16px;
  background:linear-gradient(135deg,rgba(13,17,25,.97),rgba(18,24,35,.97));
  box-shadow:0 24px 80px rgba(0,0,0,.6),0 0 120px rgba(72,215,255,.08)}
.guide-card h2{font-size:22px;margin-bottom:6px;background:linear-gradient(135deg,var(--accent),#c792ea);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
.guide-card .subtitle{color:var(--muted);font-size:13px;margin-bottom:20px;line-height:1.5}
.guide-steps{list-style:none;padding:0;margin:0 0 24px}
.guide-steps li{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid var(--line);font-size:13px;line-height:1.45;color:var(--soft)}
.guide-steps li:last-child{border-bottom:none}
.guide-steps .step-icon{flex-shrink:0;width:32px;height:32px;display:flex;align-items:center;justify-content:center;
  border-radius:8px;font-size:16px;background:rgba(72,215,255,.1);border:1px solid rgba(72,215,255,.2)}
.guide-steps .step-text b{color:var(--text);display:block;margin-bottom:2px}
.guide-btn{display:block;width:100%;padding:12px;font-size:14px;font-weight:600;color:var(--bg);
  background:linear-gradient(135deg,var(--accent),#a78bfa);border:none;border-radius:var(--radius);cursor:pointer;
  transition:.15s;letter-spacing:.02em}
.guide-btn:hover{transform:translateY(-1px);box-shadow:0 8px 24px rgba(72,215,255,.3)}

/* Legend overlay */
.legend{position:absolute;bottom:12px;left:12px;padding:12px 14px;border:1px solid var(--strong);border-radius:var(--radius);
  background:rgba(6,7,10,.82);backdrop-filter:blur(14px);z-index:3;font-size:11px;max-width:220px}
.legend.hidden{display:none}
.legend h3{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--soft);margin-bottom:8px}
.legend-item{display:flex;align-items:center;gap:8px;margin-bottom:5px;color:var(--soft)}
.legend-dot{width:10px;height:10px;border-radius:50%;flex-shrink:0}
.legend-line{width:20px;height:0;flex-shrink:0;border-top:2px solid}
.legend-line.dashed{border-top-style:dashed}
.legend-line.thick{border-top-width:3px}
.legend-sep{height:1px;background:var(--line);margin:8px 0}
.legend-toggle{position:absolute;bottom:134px;left:12px;padding:5px 10px;font-size:11px;z-index:3;
  border:1px solid var(--strong);border-radius:var(--radius);background:rgba(6,7,10,.74);backdrop-filter:blur(14px);color:var(--muted);cursor:pointer}

.help-btn{width:32px;height:32px;border-radius:50%;font-size:15px;font-weight:700;display:flex;align-items:center;
  justify-content:center;border:1px solid var(--accent);color:var(--accent);background:rgba(72,215,255,.08);cursor:pointer}
.help-btn:hover{background:rgba(72,215,255,.2)}

.narrative{padding:14px;background:linear-gradient(135deg,rgba(72,215,255,.06),rgba(199,146,234,.04));
  border:1px solid rgba(72,215,255,.15);border-radius:var(--radius);margin-bottom:10px;font-size:12px;line-height:1.5;color:var(--soft)}
.narrative strong{color:var(--text)}

/* Insight strip */
.insight-strip{position:absolute;top:12px;left:50%;transform:translateX(-50%);display:flex;gap:8px;z-index:3;pointer-events:auto;
  max-width:calc(100% - 24px);flex-wrap:wrap;justify-content:center}
.insight-card{padding:8px 12px;border:1px solid var(--strong);border-radius:var(--radius);
  background:rgba(6,7,10,.82);backdrop-filter:blur(14px);cursor:pointer;transition:.15s;min-width:min(140px,calc(50% - 8px));max-width:200px}
.insight-card:hover{border-color:var(--accent);background:rgba(72,215,255,.08)}
.insight-card .ic-label{font-size:9px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin-bottom:3px}
.insight-card .ic-value{font-size:12px;color:var(--text);line-height:1.3;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.insight-card .ic-sub{font-size:10px;color:var(--muted);margin-top:2px}

.xref{display:inline-block;padding:1px 6px;margin:1px 2px;font-size:10px;color:var(--accent);background:rgba(72,215,255,.08);max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;vertical-align:middle;
  border:1px solid rgba(72,215,255,.25);border-radius:4px;cursor:pointer;transition:.12s;font-family:var(--mono)}
.xref:hover{background:rgba(72,215,255,.2);border-color:var(--accent)}

.tab-bar{display:flex;gap:0;border-bottom:1px solid var(--line);background:rgba(0,0,0,.2)}
.tab-btn{flex:1;padding:8px 4px;font-size:11px;text-align:center;color:var(--muted);background:none;border:none;
  border-bottom:2px solid transparent;cursor:pointer;transition:.12s;border-radius:0}
.tab-btn:hover{color:var(--soft);background:rgba(255,255,255,.03)}
.tab-btn.active{color:var(--accent);border-bottom-color:var(--accent);background:rgba(72,215,255,.04)}
.tab-content{display:none}.tab-content.active{display:block}

.findings-list{max-height:300px;overflow-y:auto;scrollbar-width:thin;scrollbar-color:var(--line) transparent}
.finding-row{display:flex;align-items:center;gap:8px;padding:6px 8px;border:1px solid var(--line);border-radius:var(--radius);
  background:rgba(255,255,255,.025);margin-bottom:4px;cursor:pointer;transition:.12s;font-size:11px}
.finding-row:hover{border-color:var(--accent);background:rgba(72,215,255,.06)}
.finding-row.selected{border-color:var(--accent);background:rgba(72,215,255,.1)}
.finding-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0}
.finding-content{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--soft)}
.finding-conf{flex-shrink:0;font-family:var(--mono);font-size:10px;color:var(--muted)}
.finding-sort{display:flex;gap:4px;margin-bottom:6px}
.finding-sort button{font-size:10px;padding:2px 6px}

.view-toggle{display:flex;gap:0;margin-left:8px}
.view-toggle button{padding:4px 10px;font-size:11px;border-radius:0;border-right:none}
.view-toggle button:first-child{border-radius:var(--radius) 0 0 var(--radius)}
.view-toggle button:last-child{border-radius:0 var(--radius) var(--radius) 0;border-right:1px solid var(--line)}
.view-toggle button.active{background:rgba(72,215,255,.15);border-color:var(--accent);color:var(--accent)}

.list-view{position:absolute;inset:0;overflow-y:auto;padding:12px;background:rgba(6,7,10,.95);z-index:2;scrollbar-width:thin;scrollbar-color:var(--line) transparent}
.list-view.hidden{display:none}
.list-view table{width:100%;border-collapse:collapse;font-size:12px}
.list-view th{position:sticky;top:0;background:rgba(6,7,10,.98);text-align:left;padding:8px 6px;color:var(--muted);
  font-size:10px;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid var(--strong);cursor:pointer;user-select:none}
.list-view th:hover{color:var(--accent)}
.list-view th.sorted{color:var(--accent)}
.list-view th.sorted::after{content:" \\25BC";font-size:8px}
.list-view th.sorted.asc::after{content:" \\25B2"}
.list-view td{padding:6px;border-bottom:1px solid var(--line);color:var(--soft);cursor:pointer}
.list-view tr:hover td{background:rgba(72,215,255,.04)}

/* Progression narration bar */
.narration{position:absolute;bottom:8px;left:50%;transform:translateX(-50%);max-width:600px;width:90%;padding:8px 14px;
  border:1px solid var(--strong);border-radius:var(--radius);background:rgba(6,7,10,.86);backdrop-filter:blur(14px);
  color:var(--soft);font-size:12px;line-height:1.4;z-index:3;text-align:center;pointer-events:none;
  transition:opacity .3s;opacity:0}
.narration.show{opacity:1}

/* Convergence sparkline */
.sparkline{display:flex;align-items:end;gap:2px;height:40px;margin-top:8px}
.sparkline i{display:block;min-width:4px;flex:1;border-radius:2px 2px 0 0;transition:height .2s}

.kbd-hint{position:absolute;bottom:12px;right:180px;padding:4px 8px;border:1px solid var(--strong);border-radius:var(--radius);
  background:rgba(6,7,10,.74);backdrop-filter:blur(14px);color:var(--muted);font:10px var(--mono);z-index:3;pointer-events:none}

@keyframes fadeIn{from{opacity:0}to{opacity:1}}
@media(max-width:1100px){.workspace{grid-template-columns:260px minmax(0,1fr)}.right{position:absolute;right:0;top:60px;bottom:54px;width:min(360px,90vw);
  transform:translateX(calc(100% - 36px));transition:.16s;z-index:6;box-shadow:-8px 0 32px rgba(0,0,0,.4)}.right:hover,.right.open{transform:translateX(0)}}
@media(max-width:720px){.shell{grid-template-rows:80px minmax(0,1fr) 54px}.workspace{grid-template-columns:1fr}.left{display:none}.title h1{font-size:15px;white-space:normal}
  .guide-card{padding:20px}.guide-card h2{font-size:18px}.insight-strip{flex-wrap:wrap;max-width:90vw}}
</style>
</head>
<body>
<script id="bb-state" type="application/json">${stateJson}</script>

<!-- Guide overlay — hidden by default for poster-view first screenshot -->
<div id="guide" class="guide-overlay">
  <div class="guide-card">
    <h2>AI Reasoning Trace</h2>
    <p class="subtitle">You're looking at a visual map of how an AI analyzed <strong>"${esc(bb.task)}"</strong>. Every node is a finding. Connections show how ideas support, contradict, or replace each other.</p>
    <ul class="guide-steps">
      <li>
        <div class="step-icon">&#x1f4ca;</div>
        <div class="step-text"><b>The Graph (center)</b>Each dot is a finding. Colors = type: blue = observation, purple = analysis, yellow = calculation, green = strategy, red = gap. Drag to rearrange, scroll to zoom.</div>
      </li>
      <li>
        <div class="step-icon">&#x1f50d;</div>
        <div class="step-text"><b>Findings Index (left panel)</b>Browse all findings ranked by influence. Click any row to jump to that node. Use search and filters to narrow down.</div>
      </li>
      <li>
        <div class="step-icon">&#x1f4cb;</div>
        <div class="step-text"><b>Insights (right panel)</b>Three tabs: Detail (selected node), Insights (readiness, conflicts, depth), Sources (coverage, timeline). All entry IDs are clickable.</div>
      </li>
      <li>
        <div class="step-icon">&#x2328;</div>
        <div class="step-text"><b>Keyboard</b><b>Tab</b>/<b>Shift+Tab</b> cycle findings. <b>F</b> fit. <b>L</b> list view. <b>Esc</b> deselect. <b>1/2/3</b> switch tabs. <b>Space</b> play/pause.</div>
      </li>
    </ul>
    <button class="guide-btn" id="guideClose">Got it</button>
  </div>
</div>

<div class="shell">
  <header class="topbar">
    <div class="title">
      <h1>${esc(bb.task)}</h1>
      <div class="meta">
        <span class="chip">${entries.length} findings</span>
        <span class="chip">${signals.length} signals</span>
        <span class="chip">Iteration ${bb.iteration}</span>
        <span class="chip">${bb.documents.length} sources</span>
      </div>
    </div>
    <div class="actions">
      <div class="view-toggle">
        <button id="viewGraph" class="active" title="Graph view">Graph</button>
        <button id="viewList" title="Table view">List</button>
      </div>
      <button id="fitBtn" title="Fit all nodes (F)">Fit</button>
      <button id="shotBtn" title="Download PNG">PNG</button>
      <button class="help-btn" id="helpBtn" title="Show guide (?)">?</button>
    </div>
  </header>

  <div class="workspace">
    <aside class="left">
      <section class="panel">
        <h2>Search</h2>
        <p class="panel-desc">Find findings by content, tags, or source</p>
        <input id="search" class="search" type="search" placeholder="Type to filter findings...">
      </section>
      <section class="panel">
        <h2>Confidence Filter</h2>
        <p class="panel-desc">Show only findings above this confidence level</p>
        <input id="conf" type="range" min="0" max="100" value="0"><span id="confLbl" class="chip">0%</span>
      </section>
      <section class="panel">
        <h2>Finding Types</h2>
        <div id="typeF" class="filter-row"></div>
      </section>
      <section class="panel">
        <h2>Status</h2>
        <div id="statusF" class="filter-row"></div>
      </section>
      <section class="panel">
        <h2>Findings Index</h2>
        <p class="panel-desc">All findings ranked. Click to jump.</p>
        <div class="finding-sort">
          <button class="on" data-sort="influence">Influence</button>
          <button data-sort="confidence">Confidence</button>
          <button data-sort="iteration">Newest</button>
        </div>
        <div id="findingsIndex" class="findings-list"></div>
      </section>
      <section class="panel">
        <h2>Analysis Overview</h2>
        <div id="stats" class="mg"></div>
      </section>
      <section class="panel">
        <h2>Confidence Distribution</h2>
        <p class="panel-desc">Left = low, right = high</p>
        <div id="hist" class="hist"></div>
      </section>
      <section class="panel"><p class="footer-note">Generated by <a href="https://github.com/iqidis/ant-irys" target="_blank">Blackboard MCP</a></p></section>
    </aside>

    <main class="stage">
      <canvas id="graph"></canvas>
      <div class="hud"><span id="nVis">0</span> nodes &middot; <span id="nEdge">0</span> edges &middot; <span id="zLbl">100%</span></div>
      <div id="insightStrip" class="insight-strip"></div>
      <div id="tip" class="tooltip"></div>
      <button id="legendToggle" class="legend-toggle">Legend</button>
      <div id="legend" class="legend">
        <h3>Node Colors</h3>
        <div class="legend-item"><span class="legend-dot" style="background:#6dd6ff"></span> Observation</div>
        <div class="legend-item"><span class="legend-dot" style="background:#c792ea"></span> Analysis</div>
        <div class="legend-item"><span class="legend-dot" style="background:#ffd166"></span> Calculation</div>
        <div class="legend-item"><span class="legend-dot" style="background:#7ee787"></span> Strategy</div>
        <div class="legend-item"><span class="legend-dot" style="background:#ff7b72"></span> Gap</div>
        <div class="legend-sep"></div>
        <h3>Connections</h3>
        <div class="legend-item"><span class="legend-line" style="border-color:rgba(150,210,255,.56)"></span> Supports</div>
        <div class="legend-item"><span class="legend-line dashed" style="border-color:#ff5c7a"></span> Contradicts</div>
        <div class="legend-item"><span class="legend-line thick" style="border-color:#ffc857"></span> Supersedes</div>
        <div class="legend-sep"></div>
        <div class="legend-item" style="color:var(--muted)">Larger = higher confidence</div>
        <div class="legend-item" style="color:var(--muted)">Dashed ring = disputed</div>
      </div>
      <div id="listView" class="list-view hidden"></div>
      <div id="narration" class="narration"></div>
      <div class="kbd-hint">Tab: next &middot; F: fit &middot; L: list &middot; Space: play</div>
      <div class="minimap"><canvas id="mini"></canvas></div>
    </main>

    <aside id="dp" class="right">
      <div class="tab-bar">
        <button class="tab-btn" data-tab="detail">Detail</button>
        <button class="tab-btn active" data-tab="insights">Insights</button>
        <button class="tab-btn" data-tab="sources">Sources</button>
      </div>

      <div id="tabDetail" class="tab-content">
        <section class="panel" id="detail">
          <h2>Finding Details</h2>
          <p class="panel-desc">Click any node or row in the findings index to inspect it.</p>
          <div class="narrative">
            <strong>Quick summary:</strong> ${entries.length} findings across ${bb.documents.length} source${bb.documents.length !== 1 ? "s" : ""}.
            ${activeEntries > 0 ? `${activeEntries} active` : ""}${disputedEntries > 0 ? `, ${disputedEntries} disputed` : ""}.
            Avg confidence: ${Math.round(avgConf * 100)}%.
            ${openSignals > 0 ? `${openSignals} unresolved question${openSignals !== 1 ? "s" : ""}.` : "All questions resolved."}
          </div>
        </section>
      </div>

      <div id="tabInsights" class="tab-content active">
        <section class="panel">
          <h2>Analysis Readiness</h2>
          <p class="panel-desc">How complete the analysis is. Drops for disputes, open questions, unread sources.</p>
          <div id="conv"></div>
        </section>
        <section class="panel">
          <h2>Coverage Pressure</h2>
          <p class="panel-desc">Findings vs open questions and contradictions over time</p>
          <div id="convTrajectory"></div>
        </section>
        <section class="panel">
          <h2>Conflicting Findings</h2>
          <p class="panel-desc">Findings that disagree. Click to inspect.</p>
          <div id="contras"></div>
        </section>
        <section class="panel">
          <h2>Reasoning Depth</h2>
          <p class="panel-desc">How many layers deep the reasoning chains go</p>
          <div id="depth"></div>
        </section>
        <section class="panel">
          <h2>Unresolved Questions</h2>
          <p class="panel-desc">Questions flagged as needing investigation</p>
          <div id="qs"></div>
        </section>
      </div>

      <div id="tabSources" class="tab-content">
        <section class="panel">
          <h2>Source Documents</h2>
          <p class="panel-desc">How much of each source has been analyzed</p>
          <div id="cov"></div>
        </section>
        <section class="panel">
          <h2>Source Dependency</h2>
          <p class="panel-desc">Which sources produced the most findings and where disputes originate</p>
          <div id="srcDep"></div>
        </section>
        <section class="panel">
          <h2>Progression</h2>
          <p class="panel-desc">What changed at each iteration of analysis</p>
          <div id="progression"></div>
        </section>
      </div>
    </aside>
  </div>

  <footer class="timeline">
    <button id="playBtn" title="Replay analysis progression (Space)">Play</button>
    <input id="iterSlider" type="range" min="0" max="${bb.iteration}" value="${bb.iteration}" title="Drag to replay analysis at any iteration">
    <div id="iterLbl" class="stamp">iteration ${bb.iteration}</div>
  </footer>
</div>

<script>
(function(){
"use strict";
var bb=JSON.parse(document.getElementById("bb-state").textContent);
var entries=bb.entries||[],signals=bb.signals||[],docs=bb.documents||[];
var colors={observation:"#6dd6ff",analysis:"#c792ea",calculation:"#ffd166",strategy:"#7ee787",gap:"#ff7b72"};
var typeLabels={observation:"Observation",analysis:"Analysis",calculation:"Calculation",strategy:"Strategy",gap:"Gap"};
var types=["observation","analysis","calculation","strategy","gap"];
var statuses=["active","disputed","superseded","retracted"];
var statusLabels={active:"Active",disputed:"Disputed",superseded:"Superseded",retracted:"Retracted"};
var $=function(id){return document.querySelector(id)};
var esc=function(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]})};
var labelMap=new Map();
function shortLabel(e){
  if(labelMap.has(e.id))return labelMap.get(e.id);
  if(e.label){labelMap.set(e.id,e.label);return e.label}
  var c=e.content||"";
  var w=c.split(/[\s,.:;!?()]+/).filter(function(x){return x.length>2});
  var label=w.slice(0,5).join(" ");
  if(label.length>40)label=label.slice(0,37)+"...";
  if(!label)label=e.type;
  labelMap.set(e.id,label);return label;
}

// Guide overlay
var guideEl=$("#guide");
$("#guideClose").onclick=function(){guideEl.classList.remove("show")};
$("#helpBtn").onclick=function(){guideEl.classList.add("show")};

// Legend toggle
$("#legendToggle").onclick=function(){$("#legend").classList.toggle("hidden")};

// Right panel tabs
var tabBtns=document.querySelectorAll(".tab-btn");
var tabContents=document.querySelectorAll(".tab-content");
function switchTab(name){
  tabBtns.forEach(function(b){b.classList.remove("active");if(b.dataset.tab===name)b.classList.add("active")});
  tabContents.forEach(function(c){c.classList.remove("active")});
  var t=document.getElementById("tab"+name.charAt(0).toUpperCase()+name.slice(1));
  if(t)t.classList.add("active");
}
tabBtns.forEach(function(btn){btn.onclick=function(){switchTab(btn.dataset.tab)}});

var nodes=entries.map(function(e,i){
  var a=i*2.399963,r=80+9*Math.sqrt(i);
  return{id:e.id,e:e,x:Math.cos(a)*r,y:Math.sin(a)*r,vx:0,vy:0,r:4+(e.confidence||0)*8,vis:true};
});
var byId=new Map(nodes.map(function(n){return[n.id,n]}));
var edges=[];
entries.forEach(function(e){
  (e.supports_entries||[]).forEach(function(t){if(byId.has(t))edges.push({s:e.id,t:t,k:"supports"})});
  (e.contradicts_entries||[]).forEach(function(t){if(byId.has(t))edges.push({s:e.id,t:t,k:"contradicts"})});
  (e.supersedes_entries||[]).forEach(function(t){if(byId.has(t))edges.push({s:e.id,t:t,k:"supersedes"})});
});
var fil={types:new Set(types),statuses:new Set(statuses),min:0,q:"",iter:Math.max(bb.iteration||0)};
entries.forEach(function(e){if((e.iteration||0)>fil.iter)fil.iter=e.iteration});

// Influence scores
var influence=new Map();
entries.forEach(function(e){
  var inD=0,outD=0,contrad=0;
  edges.forEach(function(ed){if(ed.t===e.id)inD++;if(ed.s===e.id)outD++;if((ed.s===e.id||ed.t===e.id)&&ed.k==="contradicts")contrad++});
  var score=inD*2+outD+(e.addresses_signals||[]).length*3+(e.opens_questions||[]).length;
  influence.set(e.id,{score:score,inD:inD,outD:outD,contrad:contrad});
});

// Progression narration — auto-generate per-iteration summaries
var maxIter=Math.max(bb.iteration||0);
entries.forEach(function(e){maxIter=Math.max(maxIter,e.iteration||0)});
signals.forEach(function(s){maxIter=Math.max(maxIter,s.iteration_created||0)});
var iterNarration=[];
for(var ni=0;ni<=maxIter;ni++){
  var iEntries=entries.filter(function(e){return(e.iteration||0)===ni});
  var iSignals=signals.filter(function(s){return(s.iteration_created||0)===ni});
  var iTypes={};iEntries.forEach(function(e){iTypes[e.type]=(iTypes[e.type]||0)+1});
  var iContrad=0;iEntries.forEach(function(e){iContrad+=(e.contradicts_entries||[]).length});
  var iResolved=iEntries.filter(function(e){return(e.addresses_signals||[]).length>0}).length;
  var parts=[];
  if(ni===0){
    if(iTypes.observation)parts.push("Started with "+iTypes.observation+" observation"+(iTypes.observation>1?"s":""));
    if(iTypes.analysis)parts.push(iTypes.analysis+" analysis finding"+(iTypes.analysis>1?"s":""));
    if(!parts.length)parts.push(iEntries.length+" initial findings");
  }else{
    if(iEntries.length)parts.push("Added "+iEntries.length+" finding"+(iEntries.length>1?"s":""));
    if(iTypes.analysis)parts.push(iTypes.analysis+" new analys"+(iTypes.analysis>1?"es":"is"));
    if(iTypes.calculation)parts.push(iTypes.calculation+" calculation"+(iTypes.calculation>1?"s":""));
    if(iContrad)parts.push("discovered "+iContrad+" contradiction"+(iContrad>1?"s":""));
    if(iResolved)parts.push("resolved "+iResolved+" question"+(iResolved>1?"s":""));
  }
  if(iSignals.length)parts.push(iSignals.length+" new signal"+(iSignals.length>1?"s":"")+" raised");
  // Name the most important finding per iteration
  var topIterEntry=iEntries.slice().sort(function(a,b){return(influence.get(b.id)||{score:0}).score-(influence.get(a.id)||{score:0}).score})[0];
  if(topIterEntry&&ni>0)parts.push("Key: "+topIterEntry.content.slice(0,80));
  if(!parts.length)parts.push("No new findings recorded");
  iterNarration.push({iter:ni,count:iEntries.length,text:parts.join(". ")+"."});
}

// Accumulation trajectory — findings, signals, contradictions per iteration
var convTrajectory=[];
for(var ci=0;ci<=maxIter;ci++){
  var cumEntries=entries.filter(function(e){return(e.iteration||0)<=ci});
  var cumSignals=signals.filter(function(s){return(s.iteration_created||0)<=ci});
  var cumContrad=0;cumEntries.forEach(function(e){cumContrad+=(e.contradicts_entries||[]).length});
  var complexity=cumSignals.length*3+cumContrad*5;
  var cov=cumEntries.length*2;
  var cScore=Math.max(0,Math.min(100,Math.round(cov/(cov+complexity+1)*100)));
  convTrajectory.push(cScore);
}

var canvas=$("#graph"),ctx=canvas.getContext("2d"),mini=$("#mini"),mctx=mini.getContext("2d"),tip=$("#tip");
// DPI-correct: use CSS-space viewW/viewH
var viewW=0,viewH=0,dpr=1;
var cam={x:0,y:0,z:1},sel=null,hov=null,drag=null,pan=false,last={x:0,y:0},frame=0,playing=false,timer=null;
var flashId=null,flashFrame=0;
var cachedVis=[];var cachedVisEdges=[];var simSettled=false;var dirty=true;
var narrationEl=$("#narration");

function cacheVis(){
  cachedVis=nodes.filter(function(n){return n.vis});
  cachedVisEdges=edges.filter(function(e){var a=byId.get(e.s),b=byId.get(e.t);return a&&a.vis&&b&&b.vis});
}
function vis(){return cachedVis}

function w2s(x,y){return{x:(x+cam.x)*cam.z+viewW/2,y:(y+cam.y)*cam.z+viewH/2}}
function s2w(x,y){return{x:(x-viewW/2)/cam.z-cam.x,y:(y-viewH/2)/cam.z-cam.y}}

function jumpToEntry(id){
  var n=byId.get(id);if(!n)return;
  // Ensure target is visible: clear conflicting filters
  if(!n.vis){
    fil.types.add(n.e.type);fil.statuses.add(n.e.status);
    fil.iter=Math.max(fil.iter,n.e.iteration||0);
    if((n.e.confidence||0)<fil.min)fil.min=0;
    fil.q="";$("#search").value="";$("#conf").value=Math.round(fil.min*100);$("#confLbl").textContent=Math.round(fil.min*100)+"%";
    $("#iterSlider").value=fil.iter;
    syncFilterButtons();
    applyFilters();
  }
  sel=n;cam.x=-n.x;cam.y=-n.y;cam.z=Math.max(cam.z,1.15);
  $("#zLbl").textContent=Math.round(cam.z*100)+"%";
  flashId=id;flashFrame=0;simSettled=false;dirty=true;
  $("#dp").classList.add("open");switchTab("detail");
  panels();updateHash();updateFindingsIndex();
}

document.body.addEventListener("click",function(ev){
  var t=ev.target;
  if(t.dataset&&t.dataset.jump){ev.preventDefault();jumpToEntry(t.dataset.jump)}
  if(t.classList&&t.classList.contains("copy-link-btn")){
    var eid=t.dataset.entry;
    navigator.clipboard.writeText(location.origin+location.pathname+"#entry="+eid);
    t.textContent="Copied!";setTimeout(function(){t.textContent="Copy link"},1200);
  }
});

function updateHash(){if(sel)history.replaceState(null,"","#entry="+sel.id);else history.replaceState(null,"","#")}
function parseHash(){
  var h=location.hash.slice(1);if(!h)return;
  var m=h.match(/entry=([^&]+)/);
  if(m){var n=byId.get(m[1]);if(n)jumpToEntry(m[1])}
}

function xref(id){var n=byId.get(id);var lbl=n?shortLabel(n.e):id;return'<button class="xref" data-jump="'+esc(id)+'" title="'+esc(id)+'">'+esc(lbl)+'</button>'}
function xrefList(ids){return ids.map(xref).join(" ")}

function applyFilters(){
  nodes.forEach(function(n){
    var e=n.e,hay=[e.id,e.type,e.status,e.content,(e.tags||[]).join(" "),
      e.source?e.source.document:"",e.source?e.source.section:"",e.source?e.source.evidence:""].join(" ").toLowerCase();
    n.vis=fil.types.has(e.type)&&fil.statuses.has(e.status)&&(e.confidence||0)>=fil.min&&(e.iteration||0)<=fil.iter&&(!fil.q||hay.indexOf(fil.q)>=0);
  });
  cacheVis();if(sel&&!sel.vis)sel=null;simSettled=false;dirty=true;panels();updateFindingsIndex();if(isListView)renderListView();
}

function panels(){stats();histogram();detail();convergence();convTraj();contradictions();coverage();chainDepth();progression();questions();srcDependency();insightStrip()}

function stats(){
  var v=vis(),ve=v.map(function(n){return n.e});
  var avg=ve.length?ve.reduce(function(s,e){return s+(e.confidence||0)},0)/ve.length:0;
  var cr=ve.length?cachedVisEdges.filter(function(e){return e.k==="contradicts"}).length/ve.length:0;
  var visSignals=signals.filter(function(s){return(s.iteration_created||0)<=fil.iter});
  var os=visSignals.filter(function(s){return s.status==="open"}).length;
  $("#stats").innerHTML=mc(v.length,"visible findings")+mc(Math.round(avg*100)+"%","avg confidence")+mc(Math.round(cr*100)+"%","contradiction rate")+mc(os,"open questions");
}
function mc(v,l){return'<div class="mc"><b>'+esc(v)+'</b><span>'+esc(l)+'</span></div>'}

function histogram(){
  var bins=Array(10).fill(0);
  entries.forEach(function(e){bins[Math.min(9,Math.floor((e.confidence||0)*10))]++});
  var mx=Math.max.apply(null,[1].concat(bins));
  $("#hist").innerHTML=bins.map(function(c,i){
    return'<i style="height:'+Math.max(2,Math.round(c/mx*66))+'px" title="'+(i*10)+"-"+(i*10+10)+"%: "+c+' findings"></i>'
  }).join("");
}

function detail(){
  if(!sel){
    var sum='<h2>Finding Details</h2><p style="color:var(--muted);font-size:12px;margin-bottom:10px">Click any node or row to inspect it.</p>';
    sum+='<div class="narrative"><strong>Quick summary:</strong> '+entries.length+' findings across '+docs.length+' source'+(docs.length!==1?"s":"")+'. ';
    var act=entries.filter(function(e){return e.status==="active"}).length;
    var disp=entries.filter(function(e){return e.status==="disputed"}).length;
    if(act)sum+=act+' active';if(disp)sum+=', '+disp+' disputed';
    sum+='. Avg confidence: '+Math.round((entries.length?entries.reduce(function(s,e){return s+(e.confidence||0)},0)/entries.length:0)*100)+'%.</div>';
    $("#detail").innerHTML=sum;return;
  }
  var e=sel.e,s=e.source||{},inf=influence.get(e.id)||{score:0,inD:0,outD:0,contrad:0};
  var h='<h2>Finding Details</h2>';
  h+='<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;flex-wrap:wrap">';
  h+='<span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:'+(colors[e.type]||"#edf3ff")+'"></span>';
  h+='<b style="color:'+(colors[e.type]||"#edf3ff")+'">'+(typeLabels[e.type]||e.type)+'</b>';
  h+='<span class="chip">'+Math.round((e.confidence||0)*100)+'% confidence</span>';
  h+='<span class="chip">influence: '+inf.score+'</span>';
  if(e.status==="disputed")h+='<span class="chip" style="border-color:var(--bad);color:var(--bad)">Disputed</span>';
  h+='</div>';
  h+='<p style="margin:8px 0;line-height:1.5;font-size:13px">'+esc(e.content)+'</p>';
  h+='<div class="kv">';
  h+='<div>ID</div><div style="font-family:var(--mono);font-size:10px;color:var(--muted)">'+esc(e.id)+' <button class="copy-link-btn" data-entry="'+esc(e.id)+'" style="font-size:10px;padding:1px 6px;margin-left:4px">Copy link</button></div>';
  h+='<div>Status</div><div>'+(statusLabels[e.status]||e.status)+'</div>';
  h+='<div>Iteration</div><div>'+esc(e.iteration)+'</div>';
  h+='<div>Created by</div><div>'+esc(e.created_by)+'</div>';
  if((e.supports_entries||[]).length)h+='<div>Supports</div><div>'+xrefList(e.supports_entries)+'</div>';
  if((e.contradicts_entries||[]).length)h+='<div>Contradicts</div><div>'+xrefList(e.contradicts_entries)+'</div>';
  if((e.supersedes_entries||[]).length)h+='<div>Replaces</div><div>'+xrefList(e.supersedes_entries)+'</div>';
  if((e.addresses_signals||[]).length)h+='<div>Addresses</div><div>'+e.addresses_signals.map(function(id){return'<span class="chip" style="font-size:10px">'+esc(id)+'</span>'}).join(" ")+'</div>';
  if((e.tags||[]).length)h+='<div>Tags</div><div>'+e.tags.map(function(t){return'<span class="chip" style="font-size:10px">'+esc(t)+'</span>'}).join(" ")+'</div>';
  h+='</div>';
  if(s.document){
    h+='<div class="evidence"><div style="color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px">Source Evidence</div>';
    h+='<b>'+esc(s.document)+'</b>';
    if(s.section)h+='<br><span style="color:var(--muted)">Section:</span> '+esc(s.section);
    if(s.evidence)h+='<br><span style="color:var(--muted)">Quote:</span> "'+esc(s.evidence)+'"';
    h+='</div>';
  }
  var connected=[];
  edges.forEach(function(ed){
    if(ed.s===e.id&&byId.has(ed.t)){var n=byId.get(ed.t);connected.push({id:ed.t,k:ed.k,content:n.e.content})}
    if(ed.t===e.id&&byId.has(ed.s)){var n2=byId.get(ed.s);connected.push({id:ed.s,k:ed.k+"_by",content:n2.e.content})}
  });
  if(connected.length){
    h+='<div style="margin-top:12px"><div style="color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px">Connected Findings</div>';
    connected.forEach(function(c){
      var kLabel=c.k==="supports"?"supports":c.k==="contradicts"?"contradicts":c.k==="supersedes"?"supersedes":c.k==="supports_by"?"supported by":c.k==="contradicts_by"?"contradicted by":"superseded by";
      var kColor=c.k.indexOf("contradict")>=0?"var(--bad)":c.k.indexOf("supersede")>=0?"var(--warn)":"var(--good)";
      h+='<div style="display:flex;align-items:center;gap:6px;margin-bottom:6px;font-size:11px;flex-wrap:wrap">';
      h+='<span style="color:'+kColor+';font-size:10px;min-width:80px">'+kLabel+'</span>';
      h+=xref(c.id)+'</div>';
    });
    h+='</div>';
  }
  $("#detail").innerHTML=h;
}

function convergence(){
  var visSignals=signals.filter(function(s){return(s.iteration_created||0)<=fil.iter});
  var visEntries=cachedVis.map(function(n){return n.e});
  var crit=visSignals.filter(function(s){return s.status==="open"&&s.priority==="critical"}).length;
  var high=visSignals.filter(function(s){return s.status==="open"&&s.priority==="high"}).length;
  var disp=visEntries.filter(function(e){return e.status==="disputed"}).length;
  var unr=docs.filter(function(d){return d.read_status==="unread"}).length;
  var score=Math.max(0,Math.min(100,100-crit*22-high*9-disp*7-unr*11));
  var label=score>=80?"Ready":score>=50?"Needs work":"Not ready";
  var lc=score>=80?"var(--good)":score>=50?"var(--warn)":"var(--bad)";
  var h='<div style="display:flex;align-items:baseline;gap:8px;margin-bottom:6px"><span style="font-size:28px;font-weight:700;color:'+lc+'">'+score+'%</span><span style="color:'+lc+';font-size:12px">'+label+'</span></div>';
  h+='<div class="bar bar-conv"><i style="width:'+score+'%"></i></div>';
  if(crit||high||disp||unr){
    h+='<div style="margin-top:10px;font-size:11px">';
    if(crit)h+='<div style="color:var(--bad);margin-bottom:3px">'+crit+' critical question'+(crit>1?"s":"")+" unresolved</div>";
    if(high)h+='<div style="color:var(--warn);margin-bottom:3px">'+high+' high-priority question'+(high>1?"s":"")+" unresolved</div>";
    if(disp)h+='<div style="color:var(--warn);margin-bottom:3px">'+disp+' disputed finding'+(disp>1?"s":"")+"</div>";
    if(unr)h+='<div style="color:var(--muted);margin-bottom:3px">'+unr+' source'+(unr>1?"s":"")+" not yet read</div>";
    h+='</div>';
  }
  $("#conv").innerHTML=h;
}

function convTraj(){
  if(convTrajectory.length<=1){$("#convTrajectory").innerHTML='<p style="color:var(--muted);font-size:12px">Single iteration.</p>';return}
  var h='<div class="sparkline">';
  convTrajectory.forEach(function(s,i){
    var color=s>=80?"var(--good)":s>=50?"var(--warn)":"var(--bad)";
    var active=i<=fil.iter;
    h+='<i style="height:'+Math.max(2,Math.round(s/100*38))+'px;background:'+color+';opacity:'+(active?1:.25)+'" title="Iteration '+i+': '+s+'%"></i>';
  });
  h+='</div>';
  var first=convTrajectory[0],last=convTrajectory[convTrajectory.length-1],delta=last-first;
  h+='<p style="font-size:11px;color:var(--muted);margin-top:6px">';
  if(delta>0)h+='Coverage grew '+delta+' points across '+convTrajectory.length+' iterations as findings outpaced open questions.';
  else if(delta<0)h+='Complexity outpaced findings — dropped '+Math.abs(delta)+' points as new questions and contradictions accumulated.';
  else h+='Stable at '+last+'% across iterations.';
  h+='</p>';
  $("#convTrajectory").innerHTML=h;
}

function contradictions(){
  var ces=cachedVisEdges.filter(function(e){return e.k==="contradicts"}).slice(0,8);
  if(!ces.length){$("#contras").innerHTML='<p style="color:var(--good);font-size:12px">No conflicting findings.</p>';return}
  $("#contras").innerHTML=ces.map(function(e){
    var a=byId.get(e.s),b=byId.get(e.t);
    var aLabel=a?esc(a.e.content.slice(0,60)):"?";
    var bLabel=b?esc(b.e.content.slice(0,60)):"?";
    return'<div class="item"><div style="display:flex;gap:4px;margin-bottom:4px">'+xref(e.s)+'<span style="color:var(--bad);font-size:10px">vs</span>'+xref(e.t)+'</div><p>'+aLabel+'</p><p style="margin-top:2px;color:var(--bad);font-style:italic">vs: '+bLabel+'</p></div>';
  }).join("");
}

function coverage(){
  if(!docs.length){$("#cov").innerHTML='<p style="color:var(--muted);font-size:12px">No source documents.</p>';return}
  $("#cov").innerHTML=docs.map(function(d){
    var pct=d.sections&&d.sections.length?Math.round((d.sections_read||[]).length/d.sections.length*100):(d.read_status==="fully_read"?100:0);
    var st=d.read_status==="fully_read"?"Fully analyzed":d.read_status==="partially_read"?"Partially analyzed":"Not yet read";
    var sc=d.read_status==="fully_read"?"var(--good)":d.read_status==="partially_read"?"var(--warn)":"var(--muted)";
    return'<div style="margin-bottom:8px"><p style="font-size:12px;margin-bottom:2px">'+esc(d.name)+'</p><p style="font-size:10px;color:'+sc+'">'+st+(pct?' ('+pct+'%)':'')+'</p><div class="bar bar-good"><i style="width:'+pct+'%"></i></div></div>';
  }).join("");
}

function srcDependency(){
  var docFindings=new Map(),docDisputed=new Map(),unsourced=0;
  cachedVis.map(function(n){return n.e}).forEach(function(e){
    if(!e.source||!e.source.document){unsourced++;return}
    var d=e.source.document;docFindings.set(d,(docFindings.get(d)||0)+1);
    if(e.status==="disputed")docDisputed.set(d,(docDisputed.get(d)||0)+1);
  });
  var sorted=Array.from(docFindings.entries()).sort(function(a,b){return b[1]-a[1]});
  var h="";
  if(sorted.length){
    h+='<div style="font-size:11px;margin-bottom:8px">';
    sorted.forEach(function(p){
      var disp=docDisputed.get(p[0])||0;
      h+='<div style="display:flex;justify-content:space-between;margin-bottom:3px"><span style="color:var(--soft)">'+esc(p[0])+'</span><span>'+p[1]+' findings'+(disp?' <span style="color:var(--bad)">('+disp+' disputed)</span>':'')+'</span></div>';
    });
    h+='</div>';
  }
  if(unsourced)h+='<p style="font-size:11px;color:var(--warn)">'+unsourced+' finding'+(unsourced>1?"s":"")+' without source attribution</p>';
  if(!h)h='<p style="color:var(--muted);font-size:12px">No source dependency data.</p>';
  $("#srcDep").innerHTML=h;
}

function chainDepth(){
  var memo=new Map();
  var visIds=new Set(cachedVis.map(function(n){return n.id}));
  function d(id,seen){
    if(!seen)seen=new Set();if(seen.has(id))return 0;if(!visIds.has(id))return 0;if(memo.has(id))return memo.get(id);
    seen.add(id);var mx=0;
    cachedVisEdges.filter(function(e){return e.k==="supports"&&e.s===id}).forEach(function(e){mx=Math.max(mx,d(e.t,new Set(seen)))});
    var v=1+mx;memo.set(id,v);return v;
  }
  var mx=0;cachedVis.forEach(function(n){mx=Math.max(mx,d(n.id))});
  var h=mc(mx,"layers deep");
  h+='<p style="color:var(--muted);font-size:11px;margin-top:6px">';
  if(mx>=4)h+="Deep reasoning chains — thorough multi-step analysis.";
  else if(mx>=2)h+="Moderate depth with chain of thought.";
  else h+="Shallow — most findings are independent.";
  h+='</p>';
  $("#depth").innerHTML=h;
}

function progression(){
  if(iterNarration.length<=1){$("#progression").innerHTML='<p style="color:var(--muted);font-size:12px">Single-iteration analysis.</p>';return}
  var h=iterNarration.map(function(n){
    var active=n.iter<=fil.iter;
    return'<div class="item" data-it="'+n.iter+'" style="opacity:'+(active?1:.4)+'">'
      +'<b>Iteration '+n.iter+(n.iter===0?" — Start":"")+'</b>'
      +'<p>'+esc(n.text)+'</p></div>';
  }).join("");
  $("#progression").innerHTML=h;
  document.querySelectorAll("#progression [data-it]").forEach(function(el){
    el.onclick=function(){var v=parseInt(el.dataset.it);$("#iterSlider").value=v;fil.iter=v;$("#iterLbl").textContent="iteration "+v;applyFilters();var nr=iterNarration[v];if(nr)showNarration("Iteration "+v+": "+nr.text)};
  });
}

function questions(){
  var open=signals.filter(function(s){return s.status==="open"&&(s.iteration_created||0)<=fil.iter});
  if(!open.length){$("#qs").innerHTML='<p style="color:var(--good);font-size:12px">All questions resolved.</p>';return}
  $("#qs").innerHTML=open.slice(0,12).map(function(s){
    var prColor=s.priority==="critical"?"var(--bad)":s.priority==="high"?"var(--warn)":"var(--muted)";
    var jumpTarget=null;
    if(s.origin_entry&&byId.has(s.origin_entry))jumpTarget=s.origin_entry;
    return'<div class="item"'+(jumpTarget?' data-jump="'+esc(jumpTarget)+'"':'')+'><b style="color:'+prColor+'">'+esc(s.priority)+' '+esc(s.type)+'</b><p>'+esc(s.content)+'</p></div>';
  }).join("");
}

function insightStrip(){
  var strip=$("#insightStrip");var visEntries=cachedVis.map(function(n){return n.e});
  if(!visEntries.length){strip.innerHTML="";return}
  var cards=[];
  var topInf=null,topInfScore=-1;
  visEntries.forEach(function(e){var s=influence.get(e.id);if(s&&s.score>topInfScore&&e.status==="active"){topInfScore=s.score;topInf=e}});
  if(topInf)cards.push({label:"Most Central",value:topInf.content.slice(0,50),sub:"influence: "+topInfScore,id:topInf.id});

  var topConf=null,topConfVal=0;
  visEntries.forEach(function(e){if(e.type==="analysis"&&e.status==="active"&&(e.confidence||0)>topConfVal){topConfVal=e.confidence;topConf=e}});
  if(topConf)cards.push({label:"Top Conclusion",value:topConf.content.slice(0,50),sub:Math.round(topConfVal*100)+"% confidence",id:topConf.id});

  var visSignals=signals.filter(function(s){return(s.iteration_created||0)<=fil.iter});
  var critSignal=visSignals.find(function(s){return s.status==="open"&&s.priority==="critical"});
  if(!critSignal)critSignal=visSignals.find(function(s){return s.status==="open"&&s.priority==="high"});
  if(critSignal){
    var blockerId=critSignal.origin_entry&&byId.has(critSignal.origin_entry)?critSignal.origin_entry:null;
    cards.push({label:"Main Blocker",value:critSignal.content.slice(0,50),sub:critSignal.priority+" priority",id:blockerId});
  }

  var topContrad=null;
  cachedVisEdges.forEach(function(e){
    if(e.k!=="contradicts")return;
    var a=byId.get(e.s),b=byId.get(e.t);if(!a||!b)return;
    var combined=(a.e.confidence||0)+(b.e.confidence||0);
    if(!topContrad||combined>topContrad.combined)topContrad={s:e.s,t:e.t,combined:combined,content:a.e.content};
  });
  if(topContrad){var tcA=byId.get(topContrad.s),tcB=byId.get(topContrad.t);
    cards.push({label:"Key Conflict",value:topContrad.content.slice(0,50),sub:(tcA?shortLabel(tcA.e):topContrad.s)+" vs "+(tcB?shortLabel(tcB.e):topContrad.t),id:topContrad.s});
  }

  strip.innerHTML=cards.map(function(c){
    return'<div class="insight-card" '+(c.id?'data-jump="'+esc(c.id)+'"':'')+'>'
      +'<div class="ic-label">'+esc(c.label)+'</div>'
      +'<div class="ic-value">'+esc(c.value)+'</div>'
      +'<div class="ic-sub">'+esc(c.sub)+'</div></div>';
  }).join("");
}

// Findings index
var currentSort="influence";
function updateFindingsIndex(){
  var sorted=vis().slice().sort(function(a,b){
    if(currentSort==="confidence")return(b.e.confidence||0)-(a.e.confidence||0);
    if(currentSort==="iteration")return(b.e.iteration||0)-(a.e.iteration||0);
    var ai=influence.get(a.id)||{score:0},bi=influence.get(b.id)||{score:0};return bi.score-ai.score;
  });
  var h=sorted.slice(0,50).map(function(n){
    var e=n.e,isSelected=sel&&sel.id===e.id;
    return'<div class="finding-row'+(isSelected?" selected":"")+'" data-jump="'+esc(e.id)+'">'
      +'<span class="finding-dot" style="background:'+(colors[e.type]||"#edf3ff")+'"></span>'
      +'<span class="finding-content">'+esc(e.content.slice(0,60))+'</span>'
      +'<span class="finding-conf">'+Math.round((e.confidence||0)*100)+'%</span></div>';
  }).join("");
  if(!h)h='<p style="color:var(--muted);font-size:12px;padding:4px">No findings match filters.</p>';
  $("#findingsIndex").innerHTML=h;
}
document.querySelectorAll("[data-sort]").forEach(function(btn){
  btn.onclick=function(){
    document.querySelectorAll("[data-sort]").forEach(function(b){b.classList.remove("on")});
    btn.classList.add("on");currentSort=btn.dataset.sort;updateFindingsIndex();
  };
});

// List view — uses filtered entries
var listViewEl=$("#listView");
var listSortCol="influence",listSortAsc=false;
function renderListView(){
  var filtered=vis().map(function(n){return n.e});
  var sorted=filtered.slice().sort(function(a,b){
    if(listSortCol==="confidence")return listSortAsc?(a.confidence||0)-(b.confidence||0):(b.confidence||0)-(a.confidence||0);
    if(listSortCol==="type")return listSortAsc?a.type.localeCompare(b.type):b.type.localeCompare(a.type);
    if(listSortCol==="iteration")return listSortAsc?(a.iteration||0)-(b.iteration||0):(b.iteration||0)-(a.iteration||0);
    if(listSortCol==="status")return listSortAsc?a.status.localeCompare(b.status):b.status.localeCompare(a.status);
    var ai=(influence.get(a.id)||{score:0}).score,bi=(influence.get(b.id)||{score:0}).score;
    return listSortAsc?ai-bi:bi-ai;
  });
  function thC(col){return col===listSortCol?(listSortAsc?"sorted asc":"sorted"):""}
  var h='<table><thead><tr>';
  h+='<th class="'+thC("type")+'" data-lcol="type">Type</th>';
  h+='<th>Content</th>';
  h+='<th class="'+thC("confidence")+'" data-lcol="confidence">Conf</th>';
  h+='<th class="'+thC("influence")+'" data-lcol="influence">Influence</th>';
  h+='<th class="'+thC("status")+'" data-lcol="status">Status</th>';
  h+='<th class="'+thC("iteration")+'" data-lcol="iteration">Iter</th>';
  h+='</tr></thead><tbody>';
  sorted.forEach(function(e){
    var inf=influence.get(e.id)||{score:0};
    h+='<tr data-jump="'+esc(e.id)+'">';
    h+='<td><span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:'+(colors[e.type]||"#edf3ff")+';margin-right:6px"></span>'+(typeLabels[e.type]||e.type)+'</td>';
    h+='<td style="max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(e.content)+'</td>';
    h+='<td>'+Math.round((e.confidence||0)*100)+'%</td><td>'+inf.score+'</td>';
    h+='<td>'+(statusLabels[e.status]||e.status)+'</td><td>'+(e.iteration||0)+'</td></tr>';
  });
  h+='</tbody></table>';
  listViewEl.innerHTML=h;
  listViewEl.querySelectorAll("[data-lcol]").forEach(function(th){
    th.onclick=function(){if(listSortCol===th.dataset.lcol)listSortAsc=!listSortAsc;else{listSortCol=th.dataset.lcol;listSortAsc=false}renderListView()};
  });
}
var isListView=false;
$("#viewGraph").onclick=function(){isListView=false;listViewEl.classList.add("hidden");$("#viewGraph").classList.add("active");$("#viewList").classList.remove("active")};
$("#viewList").onclick=function(){isListView=true;renderListView();listViewEl.classList.remove("hidden");$("#viewList").classList.add("active");$("#viewGraph").classList.remove("active")};

function tick(){
  frame++;
  if(!simSettled){simulate();dirty=true}
  if(flashId)dirty=true;
  if(dirty){draw();dirty=false}
  requestAnimationFrame(tick);
}

function simulate(){
  var v=vis();if(!v.length){simSettled=true;return}
  var rep=v.length>260?520:900,totalV=0;
  for(var i=0;i<v.length;i++)for(var j=i+1;j<v.length;j++){
    var a=v[i],b=v[j],dx=b.x-a.x,dy=b.y-a.y,d2=Math.max(24,dx*dx+dy*dy),d=Math.sqrt(d2),f=rep/d2;
    a.vx-=dx/d*f;a.vy-=dy/d*f;b.vx+=dx/d*f;b.vy+=dy/d*f;
  }
  cachedVisEdges.forEach(function(e){
    var a=byId.get(e.s),b=byId.get(e.t);
    if(!a||!b)return;
    var dx=b.x-a.x,dy=b.y-a.y,d=Math.max(1,Math.hypot(dx,dy)),ideal=e.k==="contradicts"?170:118,f=(d-ideal)*.0024;
    a.vx+=dx/d*f;a.vy+=dy/d*f;b.vx-=dx/d*f;b.vy-=dy/d*f;
  });
  v.forEach(function(n){
    if(drag===n)return;
    n.vx+=-n.x*.0008;n.vy+=-n.y*.0008;n.vx*=.86;n.vy*=.86;n.x+=n.vx;n.y+=n.vy;
    totalV+=Math.abs(n.vx)+Math.abs(n.vy);
  });
  if(totalV<0.05*v.length&&frame>120)simSettled=true;
}

function draw(){
  ctx.setTransform(dpr,0,0,dpr,0,0);
  ctx.clearRect(0,0,viewW,viewH);
  var rel=conn(hov||sel);
  cachedVisEdges.forEach(function(e){drawEdge(e,rel)});
  cachedVis.forEach(function(n){drawNode(n,rel)});
  drawMini();
  if(flashId){
    flashFrame++;
    var fn=byId.get(flashId);
    if(fn&&flashFrame<45){
      var fp=w2s(fn.x,fn.y),alpha=Math.max(0,1-flashFrame/45),radius=(20+flashFrame*1.5)*cam.z;
      ctx.save();ctx.globalAlpha=alpha*.4;ctx.strokeStyle=colors[fn.e.type]||"#48d7ff";ctx.lineWidth=3;
      ctx.beginPath();ctx.arc(fp.x,fp.y,radius,0,Math.PI*2);ctx.stroke();ctx.restore();
    }else flashId=null;
  }
  $("#nVis").textContent=cachedVis.length;
  $("#nEdge").textContent=cachedVisEdges.length;
}

function conn(n){
  var s=new Set();if(!n)return s;s.add(n.id);
  edges.forEach(function(e){if(e.s===n.id)s.add(e.t);if(e.t===n.id)s.add(e.s)});
  return s;
}

function drawEdge(e,rel){
  var a=byId.get(e.s),b=byId.get(e.t);if(!a||!b)return;
  var pa=w2s(a.x,a.y),pb=w2s(b.x,b.y),act=!rel.size||(rel.has(a.id)&&rel.has(b.id));
  ctx.save();ctx.globalAlpha=act?.82:.08;ctx.lineWidth=e.k==="contradicts"?2.2:1.2;
  ctx.strokeStyle=e.k==="contradicts"?"#ff5c7a":e.k==="supersedes"?"#ffc857":"rgba(150,210,255,.56)";
  if(e.k!=="supports")ctx.setLineDash(e.k==="contradicts"?[7,7]:[4,8]);
  ctx.lineDashOffset=e.k==="contradicts"?-frame*.45:0;
  ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();
  var angle=Math.atan2(pb.y-pa.y,pb.x-pa.x),sz=8*cam.z;
  ctx.fillStyle=ctx.strokeStyle;ctx.setLineDash([]);
  ctx.beginPath();ctx.moveTo(pb.x,pb.y);ctx.lineTo(pb.x-sz*Math.cos(angle-.35),pb.y-sz*Math.sin(angle-.35));
  ctx.lineTo(pb.x-sz*Math.cos(angle+.35),pb.y-sz*Math.sin(angle+.35));ctx.closePath();ctx.fill();
  ctx.restore();
}

function drawNode(n,rel){
  var p=w2s(n.x,n.y),act=!rel.size||rel.has(n.id),r=(n.r+(sel===n?5:hov===n?3:0))*cam.z;
  ctx.save();ctx.globalAlpha=act?1:.18;
  ctx.beginPath();ctx.arc(p.x,p.y,Math.max(3,r),0,Math.PI*2);
  ctx.fillStyle=colors[n.e.type]||"#edf3ff";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=sel===n||hov===n?28:12;ctx.fill();
  ctx.shadowBlur=0;
  if(n.e.status==="disputed"){ctx.strokeStyle="#ff5c7a";ctx.lineWidth=3;ctx.setLineDash([4,4]);ctx.lineDashOffset=-frame*.3;ctx.stroke();ctx.setLineDash([]);}
  else{ctx.strokeStyle="rgba(255,255,255,.6)";ctx.lineWidth=1.2;ctx.stroke();}
  if(cam.z>.7||sel===n||hov===n){
    ctx.fillStyle="rgba(237,243,255,.88)";ctx.font=Math.max(9,11*cam.z)+"px var(--sans)";
    ctx.fillText(shortLabel(n.e),p.x+r+5,p.y+4);
  }
  ctx.restore();
}

function drawMini(){
  mctx.clearRect(0,0,mini.width,mini.height);
  mctx.fillStyle="rgba(255,255,255,.03)";mctx.fillRect(0,0,mini.width,mini.height);
  var v=cachedVis;if(!v.length)return;
  var xs=v.map(function(n){return n.x}),ys=v.map(function(n){return n.y});
  var mnX=Math.min.apply(null,xs),mxX=Math.max.apply(null,xs),mnY=Math.min.apply(null,ys),mxY=Math.max.apply(null,ys);
  var s=Math.min(mini.width/Math.max(1,mxX-mnX),mini.height/Math.max(1,mxY-mnY))*.82;
  v.forEach(function(n){mctx.fillStyle=colors[n.e.type];mctx.beginPath();mctx.arc((n.x-mnX)*s+8,(n.y-mnY)*s+8,2,0,Math.PI*2);mctx.fill()});
  var tl=s2w(0,0),br=s2w(viewW,viewH);
  mctx.strokeStyle="rgba(72,215,255,.5)";mctx.lineWidth=1;
  mctx.strokeRect((tl.x-mnX)*s+8,(tl.y-mnY)*s+8,(br.x-tl.x)*s,(br.y-tl.y)*s);
}

function nearest(x,y,tol){
  var best=null,bd=1e9;
  cachedVis.forEach(function(n){var p=w2s(n.x,n.y),d=Math.hypot(p.x-x,p.y-y);if(d<bd&&d<n.r*cam.z+tol){best=n;bd=d}});
  return best;
}

function selectNode(n){if(!n)return;sel=n;dirty=true;$("#dp").classList.add("open");switchTab("detail");panels();updateHash();updateFindingsIndex()}

function fit(){
  var v=cachedVis;if(!v.length)return;
  var xs=v.map(function(n){return n.x}),ys=v.map(function(n){return n.y});
  var mnX=Math.min.apply(null,xs),mxX=Math.max.apply(null,xs),mnY=Math.min.apply(null,ys),mxY=Math.max.apply(null,ys);
  cam.z=Math.max(.25,Math.min(1.8,Math.min(viewW/(mxX-mnX+220),viewH/(mxY-mnY+220))));
  cam.x=-(mnX+mxX)/2;cam.y=-(mnY+mxY)/2;
  $("#zLbl").textContent=Math.round(cam.z*100)+"%";dirty=true;
}

function resize(){
  var r=canvas.parentElement.getBoundingClientRect();
  dpr=window.devicePixelRatio||1;
  viewW=r.width;viewH=r.height;
  canvas.width=Math.round(viewW*dpr);canvas.height=Math.round(viewH*dpr);
  canvas.style.width=viewW+"px";canvas.style.height=viewH+"px";
  var mr=mini.getBoundingClientRect();mini.width=Math.round(mr.width*dpr);mini.height=Math.round(mr.height*dpr);
  dirty=true;
}
window.onresize=resize;resize();cacheVis();
// Pre-settle: run simulation before first draw for deterministic poster frame
for(var ps=0;ps<80;ps++){frame++;simulate()}
fit();applyFilters();updateFindingsIndex();requestAnimationFrame(tick);

// Narration during play
function showNarration(text){
  narrationEl.textContent=text;narrationEl.classList.add("show");
  clearTimeout(narrationEl._t);narrationEl._t=setTimeout(function(){narrationEl.classList.remove("show")},2500);
}

// Keyboard shortcuts
document.onkeydown=function(e){
  if(e.target.tagName==="INPUT"||e.target.tagName==="TEXTAREA"||e.target.tagName==="BUTTON"||e.target.tagName==="SELECT")return;
  if(e.key==="f"||e.key==="F"){e.preventDefault();fit()}
  else if(e.key==="l"||e.key==="L"){e.preventDefault();isListView?$("#viewGraph").click():$("#viewList").click()}
  else if(e.key==="Escape"){sel=null;panels();updateHash();updateFindingsIndex()}
  else if(e.key==="?"){e.preventDefault();guideEl.classList.add("show")}
  else if(e.key==="1"){switchTab("detail")}
  else if(e.key==="2"){switchTab("insights")}
  else if(e.key==="3"){switchTab("sources")}
  else if(e.key===" "){e.preventDefault();$("#playBtn").click()}
  else if(e.key==="Tab"){
    e.preventDefault();
    var v=cachedVis;if(!v.length)return;
    var idx=sel?v.indexOf(sel):-1;
    idx=e.shiftKey?(idx<=0?v.length-1:idx-1):(idx>=v.length-1?0:idx+1);
    jumpToEntry(v[idx].id);
  }
};

// Controls
$("#search").oninput=function(e){fil.q=e.target.value.trim().toLowerCase();applyFilters()};
$("#conf").oninput=function(e){fil.min=+e.target.value/100;$("#confLbl").textContent=e.target.value+"%";applyFilters()};
$("#iterSlider").oninput=function(e){fil.iter=+e.target.value;$("#iterLbl").textContent="iteration "+fil.iter;applyFilters()};
$("#fitBtn").onclick=fit;
$("#shotBtn").onclick=function(){var a=document.createElement("a");a.download="blackboard-"+bb.id+".png";a.href=canvas.toDataURL("image/png");a.click()};
$("#playBtn").onclick=function(){
  playing=!playing;$("#playBtn").textContent=playing?"Pause":"Play";
  if(playing){
    fil.iter=0;$("#iterSlider").value=0;$("#iterLbl").textContent="iteration 0";applyFilters();
    var narr=iterNarration[0];if(narr)showNarration("Iteration 0: "+narr.text);
    timer=setInterval(function(){
      var s=$("#iterSlider"),n=+s.value+1;
      if(n>+s.max){clearInterval(timer);playing=false;$("#playBtn").textContent="Play";return}
      s.value=n;fil.iter=n;$("#iterLbl").textContent="iteration "+n;applyFilters();
      var narr2=iterNarration[n];if(narr2)showNarration("Iteration "+n+": "+narr2.text);
    },1800);
  }else clearInterval(timer);
};

// Canvas interaction
var panMoved=false;
canvas.onpointerdown=function(e){
  var n=nearest(e.offsetX,e.offsetY,16);last={x:e.offsetX,y:e.offsetY};panMoved=false;
  if(n){drag=n;selectNode(n)}else{pan=true}
  canvas.setPointerCapture(e.pointerId);
};
canvas.onpointermove=function(e){
  var dx=e.offsetX-last.x,dy=e.offsetY-last.y;last={x:e.offsetX,y:e.offsetY};
  if(drag){var p=s2w(e.offsetX,e.offsetY);drag.x=p.x;drag.y=p.y;simSettled=false;dirty=true}
  else if(pan){cam.x+=dx/cam.z;cam.y+=dy/cam.z;dirty=true;if(Math.abs(dx)>2||Math.abs(dy)>2)panMoved=true}
  else{
    dirty=true;
    hov=nearest(e.offsetX,e.offsetY,13);
    tip.style.display=hov?"block":"none";
    if(hov){
      tip.style.left=Math.min(e.clientX+16,innerWidth-360)+"px";
      tip.style.top=Math.min(e.clientY+16,innerHeight-140)+"px";
      var tipType=typeLabels[hov.e.type]||hov.e.type;
      var tipConf=Math.round((hov.e.confidence||0)*100);
      var tipInf=influence.get(hov.id)||{score:0};
      tip.innerHTML='<div style="display:flex;align-items:center;gap:6px;margin-bottom:4px">'
        +'<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:'+colors[hov.e.type]+'"></span>'
        +'<b style="color:'+colors[hov.e.type]+'">'+esc(tipType)+'</b>'
        +'<span style="color:var(--muted);font-size:10px">'+tipConf+'% &middot; influence '+tipInf.score+'</span></div>'
        +'<div style="margin-bottom:4px;line-height:1.4">'+esc(hov.e.content.slice(0,200))+'</div>'
        +'<div style="color:var(--muted);font-size:10px">Click to inspect &middot; Drag to move</div>';
    }
  }
};
canvas.onpointerup=function(e){
  if(pan&&!panMoved&&!drag){sel=null;panels();updateHash();updateFindingsIndex();dirty=true}
  drag=null;pan=false;canvas.releasePointerCapture(e.pointerId);
};
canvas.onpointerleave=function(){hov=null;tip.style.display="none";dirty=true};
canvas.onwheel=function(e){
  e.preventDefault();
  var before=s2w(e.offsetX,e.offsetY);
  cam.z=Math.max(.18,Math.min(4,cam.z*(e.deltaY>0?.9:1.1)));
  var after=s2w(e.offsetX,e.offsetY);
  cam.x+=after.x-before.x;cam.y+=after.y-before.y;
  $("#zLbl").textContent=Math.round(cam.z*100)+"%";dirty=true;
};

function syncFilterButtons(){
  $("#typeF").querySelectorAll("button").forEach(function(b,i){var t=types[i];if(t)b.classList.toggle("on",fil.types.has(t))});
  $("#statusF").querySelectorAll("button").forEach(function(b,i){var s=statuses[i];if(s)b.classList.toggle("on",fil.statuses.has(s))});
}

// Filter buttons
types.forEach(function(t){
  var b=document.createElement("button");b.textContent=typeLabels[t]||t;b.className="on";b.style.fontSize="11px";b.style.padding="3px 8px";
  b.style.borderLeftColor=colors[t];b.style.borderLeftWidth="3px";
  b.title={observation:"Facts from sources",analysis:"Interpretations and conclusions",calculation:"Derived results",strategy:"Approach decisions",gap:"Missing information"}[t]||"";
  b.onclick=function(){fil.types.has(t)?fil.types.delete(t):fil.types.add(t);b.classList.toggle("on");applyFilters()};
  $("#typeF").appendChild(b);
});
statuses.forEach(function(s){
  var b=document.createElement("button");b.textContent=statusLabels[s]||s;b.className="on";b.style.fontSize="11px";b.style.padding="3px 8px";
  b.title={active:"Currently valid",disputed:"Conflicts with others",superseded:"Replaced by newer",retracted:"Withdrawn"}[s]||"";
  b.onclick=function(){fil.statuses.has(s)?fil.statuses.delete(s):fil.statuses.add(s);b.classList.toggle("on");applyFilters()};
  $("#statusF").appendChild(b);
});

parseHash();
})();
</script>
</body>
</html>`;

  return { html, counts: { nodes: entries.length, edges: edges.length } };
}
