import json

from src.swarm.prompt_audit import (
    PromptAuditContext,
    audit_prompt,
    summarize_records,
)


def test_prompt_audit_flags_forbidden_provenance(tmp_path, monkeypatch):
    monkeypatch.setenv("SWARM_PROMPT_AUDIT", "1")

    record = audit_prompt(
        "Use the generated completeness criteria, not scorer data.",
        PromptAuditContext(
            stage="unit",
            output_dir=str(tmp_path),
            provenance=["user.instruction", "benchmark.match_criteria"],
        ),
    )

    assert record["forbidden_provenance_hits"] == ["benchmark.match_criteria"]
    assert record["forbidden_text_hits"] == []

    path = tmp_path / "swarm" / "prompt_audit.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    assert data["summary"]["records"] == 1
    assert data["summary"]["forbidden_provenance_hits"] == 1


def test_prompt_audit_does_not_ban_clean_criteria_word(tmp_path, monkeypatch):
    monkeypatch.setenv("SWARM_PROMPT_AUDIT", "1")

    record = audit_prompt(
        "SEED COMPLETENESS CRITERIA GENERATED BY THE SYSTEM",
        {
            "stage": "unit",
            "output_dir": str(tmp_path),
            "provenance": ["swarm.seed_generated"],
        },
    )

    assert record["forbidden_provenance_hits"] == []
    assert record["forbidden_text_hits"] == []


def test_summarize_records_counts_stages():
    summary = summarize_records([
        {"stage": "a", "forbidden_provenance_hits": [], "forbidden_text_hits": []},
        {"stage": "a", "forbidden_provenance_hits": ["x"], "forbidden_text_hits": []},
        {"stage": "b", "forbidden_provenance_hits": [], "forbidden_text_hits": ["y"]},
    ])

    assert summary["records"] == 3
    assert summary["stages"] == {"a": 2, "b": 1}
    assert summary["forbidden_provenance_hits"] == 1
    assert summary["forbidden_text_hits"] == 1
